# Generated by Django 3.2.24 on 2024-04-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobnotification'),
        ('app', '0006_alter_subscriptionpayment_created_at_and_more'),
    ]

    operations = [
    ]
